name: 👾 Report Mistakes in Documentation
description: Help us to build a better guidelines for you 
labels: [bug]
body:
  
  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines?
      options:
        - label: I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).
          required: true

  - type: input
    attributes:
      label: Full URL
      description: Be careful while you copy the link.
      placeholder: e.g https://snigdhaos.org/documentation/installation/download_snigdha_os
    validations:
      required: true
  
  - type: dropdown
    attributes:
      label: What Type of Mistake we made?
      description: You can select more than one options.
      multiple: true
      options:
        - Spelling Mistake
        - Wrong Documentation or Code Not Working
        - Incomplete Documentation
    validations:
      required: true

  - type: textarea
    attributes:
      label: Write the correction
      description: It is not necessary to write here. You can directly edit the [documentation](https://github.com/Snigdha-OS/documentation/tree/master/docs) repository and create pull request.
      placeholder: e.g L10 to L12 "Wite down your correction or edit the code directly."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Your PC Specification
      description: |
        Include as many relevant details about the environment you experienced the bug in.
        > run `cat /etc/os-release` on terminal to see **OS Build ID**
      value: |
        - CPU: [e.g i5 1335U]
        - RAM: [e.g 2 GiB]
        - STORAGE: [e.g SSD/HDD]
        - Snigdha OS Build: [e.g arctic]
        - Snigdha OS Version: [e.g 4.5]

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days so we can still delegate this to someone else.
      options:
        - label: I'd be willing to fix this bug myself.
