name: 📝 Proposal
description: Propose a non-trivial change to Snigdha OS or in Packages
labels: [proposal]
body:
  - type: markdown
    attributes:
      value: |
        Common reasons for proposals include:

        - Bumping a critical dependency's major version;
        - A significant improvement to a CLI command;
        - Significant refactor;
        - ...

        Remember, this is not for feature requests. We give you maximum freedom to write an elaborated proposal illustrating why you think the change is beneficial for us and for users, and what steps we should take to turn this into reality. You should not use this to ditch the feature request or bug template; such action could make us identify the issue wrongly and close it without doing anything.

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).
          required: true

  - type: textarea
    attributes:
      label: Motivation
      description: A clear and concise description of what the proposal is.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 7 days after a maintainer's approval so we can still delegate this to someone else.

        Proposals usually involve significant code changes, so please reach consensus with the maintainers before rushing to implement it. This ensures that you don't waste your time and we don't waste ours reading the large diffs.
      options:
        - label: I'd be willing to do some initial work on this proposal myself.